### ISSUE TITLE
Suggestion to create a pypi package for this

### ISSUE THREAD

**Issue by franklingu** [sharkdp/shell-functools#11]
I think this is cool and a pypi package for it should be good, or at least a shell for installing it to maybe $(HOME) and add to path

**Comment by sharkdp** [comment]
Sounds great. Unfortunately, I don't have any experience with pypi, so any help would be greatly appreciated.

**Comment by franklingu** [comment]
I will make a fork and pull request later. I had a little experience and will try to apply this

**Comment by SpotlightKid** [comment]
Yes, please, that would be great. So we can install this easily with [pipsi}(https://pypi.python.org/pypi/pipsi).

**Comment by franklingu** [comment]
Can close this and #13 ?

**Comment by sharkdp** [comment]
Yes, thanks.

The package has been uploaded to pypi.
