### ISSUE TITLE
Add version, author and more meta info to ft/__init__.py

### ISSUE THREAD

**Issue by franklingu** [sharkdp/shell-functools#12]
this is related to "making it a pip package". most users will do `import ft; print(ft.__version__)` to verify it is installed successfully

**Comment by sharkdp** [comment]
Sounds good!

**Comment by sharkdp** [comment]
Is this still needed?

**Comment by franklingu** [comment]
I think this can be closed. now we can just print(ft.__version__)

I believe readme needs to be updated to include installation guide using pip. it is much cleaner option than changing PATH

**Comment by franklingu** [comment]
just saw your commit for the part about pip. :+1:
