### ISSUE TITLE
Commands not installed

### ISSUE THREAD

**Issue by Pawamoy** [sharkdp/shell-functools#27]
I just tried to install shell-functools through [pipsi](https://github.com/mitsuhiko/pipsi) and some commands were not installed.

I only have access to filter, foldl, ft-functions, and map.

I also tried with a regular virtualenv (python 3.5.5) and a pip install, with the same result.

I suspect the Python scripts in the `ft` folder not to be picked while creating the dist/wheel.

**Comment by sharkdp** [comment]
`take_while`, `sort_by` and `foldl1` have been added after the latest release. I should create a new one.

**Comment by Pawamoy** [comment]
Hmmmm that's why :smile: ! Thanks for the info :)

**Comment by sharkdp** [comment]
New version has been released: https://pypi.org/project/shell-functools/
