### ISSUE TITLE
Problem installing in Python3.6 env

### ISSUE THREAD

**Issue by msalvaris** [sharkdp/shell-functools#31]
When I try to pip install shell-functools in a Python3.6 env I get the following:

Downloading https://files.pythonhosted.org/packages/71/89/8badd56d0264f7a38e3832dac59ad1026ef72f642638b3249ae58b87325a/shell-functools-0.3.0.tar.gz    Complete output from command python setup.py egg_info:    
Traceback (most recent call last):      
  File "<string>", line 1, in <module>      
  File "/tmp/pip-build-aobq6968/shell-functools/setup.py", line 34, in <module>        
    LONG_DESC = ifile.read()      
File "/opt/conda/envs/py3.6/lib/python3.6/encodings/ascii.py", line 26, in decode        
    return codecs.ascii_decode(input, self.errors)[0]    
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6071: ordinal not in range(128)

**Comment by sharkdp** [comment]
Thank you for your feedback.

I can not reproduce this:
```
▶ virtualenv test-shell-functools
Using base prefix '/usr'
New python executable in /tmp/test-shell-functools/bin/python
Installing setuptools, pip, wheel...done.

▶ source ./test-shell-functools/bin/activate

▶ python --version
Python 3.6.5

▶ pip install shell-functools
Collecting shell-functools
  Downloading https://files.pythonhosted.org/packages/71/89/8badd56d0264f7a38e3832dac59ad1026ef72f642638b3249ae58b87325a/shell-functools-0.3.0.tar.gz
Building wheels for collected packages: shell-functools
  Running setup.py bdist_wheel for shell-functools ... done
  Stored in directory: /home/shark/.cache/pip/wheels/32/95/b6/e720951d505fd4a61404b81d6aaefb1c71c4807dbb084c0a27
Successfully built shell-functools
Installing collected packages: shell-functools
Successfully installed shell-functools-0.3.0

▶ which map
/tmp/test-shell-functools/bin/map

▶ seq 3 | map add 10
11
12
13
```

**Comment by msalvaris** [comment]
Thanks for the quick reply.

I am using a conda env inside a docker container. Tried it outside the docker container and it was fine. Should have checked this before posting. I will investigate further to see if I can uncover anything more.

Thanks again.

**Comment by msalvaris** [comment]
OK, figured it out. The locale was not UTF8 in the container. Should have realised this as soon as it started complaining about UnicodeDecodeError. Thanks again.
