### ISSUE TITLE
Add a way to negate the `filter` criterion.

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/shell-functools#4]
... in order to say something like `find | filter --not is_dir`

Some options:
- add a `--not`/`-n` option to `filter`
- provide a new command `reject`
- Add a composition operator (`:`?) in order to write `find | filter is_dir : negate`.

**Comment by sharkdp** [comment]
In the same way, we should support a way to reverse the sorting order in `sort_by`.

**Comment by vegarsti** [comment]
Should this issue be closed?

**Comment by vegarsti** [comment]
Should this issue be closed?
