### ISSUE TITLE
is_link does not detect links

### ISSUE THREAD

**Issue by MaxG87** [sharkdp/shell-functools#43]
When tried to get started with shell-functools, I noticed that `is_link` does not work as I expected it to do.

I am on Debian stable. I executed the following steps:
```
$ touch /tmp/ft-source
$ ln -s /tmp/ft-source /tmp/ft-destination
$ ls /tmp/ft-* | map is_link
False
False
```
I would expect that one output is `True`. Indeed, if I execute `os.path.islink("/tmp/ft-destination")` in IPython, it returns `True`.

I tried to produce a Docker to reproduce the error. Interestingly, there everything works as I expect it to do.
```dockerfile
FROM python:3.9.8-slim-bullseye

RUN python -m pip install shell-functools
RUN touch /tmp/ft-source
RUN ln -s /tmp/ft-source /tmp/ft-destination
CMD ls /tmp/ft-* | map is_link
```

Am I missing something about how `is_link` is supposed to work? Or is this a bug?

**Comment by sharkdp** [comment]
Hm. I can't reproduce this either:
```
▶ ls /tmp/ft-* | map is_link
True
False
```

Maybe `/tmp` is a strange file system? But then why would the direct `os.path.islink` call return `True`? Very strange. I have no idea what's going on.

**Comment by MaxG87** [comment]
Thank you for having a look into this.

I was afraid that this wont be reproducible. If I manage to come up with something more robust I will reopen the issue.

**Comment by MaxG87** [comment]
I found the culprit!
I use `exa`, which I aliased to `ls` because I cannot relearn to use `exa` directly. However, `exa` changes behaviour if its destination is not a shell directly:

```
$ exa /tmp/ft-* | cat
/tmp/ft-destination -> /tmp/ft-source
/tmp/ft-source
``

Thus, the first line is not a file but some arbitrary string.

Should `is_link` print a warning/exit with error if its input is not a file?

**Comment by sharkdp** [comment]
Ah, interesting. Strange that `exa` prints something like `a -> b` to a non-interactive terminal.

> Should `is_link` print a warning/exit with error if its input is not a file?

I don't think so. I would expect `is_link` to return `True` if the target is a link, and `False` in all other cases.
