### ISSUE TITLE
Add foldl1

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/shell-functools#6]
Like `foldl` but without the initial accumulator argument:
``` bash
> seq 10 | foldl1 mul
3628800
```

**Comment by sharkdp** [comment]
This should probably re-use the existing `Foldl` class (see how `TakeWhile` uses `Filter`).

**Comment by guilhermeleobas** [comment]
Hi,

I'd like to work on this one

regards

**Comment by sharkdp** [comment]
Fixed via #23
